services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
  tg-bot:
    build:
      context: tg-bot/
    restart: always
    env_file:
      - .env
    environment:
      SERVER_URL: http://backend:8000/api
