services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    env_file:
      - .env
  tg-bot:
    build:
      context: tg-bot/
    env_file:
      - .env
    network_mode: host
