[project]
name = "tg-bot"
version = "0.0.0"
requires-python = ">=3.13"
dependencies = [
  "aiogram>=3.20.0.post0",
  "python-dotenv>=1.1.0",
  "requests>=2.32.3",
]

[tool.pyright]
venvPath = "./"
venv = ".venv/"
